figure(1)
plot(0:50,str(8,20,0:50),'b', 0:50,str(6,20,0:50),'g')
xlabel('Connection length') 
ylabel('Connection strength')
legend('Ascending','Descending')
title('Uniform Coupling Asymmetry')
figure(2)
plot(0:50,str(1,40,0:50),'b',0:50,str(10,5,0:50),'g')
title('Nonuniform Coupling Asymmtetry')
legend('Ascending','Descending')
xlabel('connection length') 
ylabel('connection strength')